# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

a1 = Album.create(cover: "http://s3.amazonaws.com/codecademy-content/projects/3/bass-music/my-beautiful-dark-twisted-fantasy.jpg", title: "My Beautiful Dark Twisted Fantasy", artiste: "Kanye West")
Track.create(name: "Dark Fantasy", duration: 5, album_id: a1.id)
Track.create(name: "Gorgeous", duration: 6, album_id: a1.id)
Track.create(name: "Power", duration: 5, album_id: a1.id)
Track.create(name: "All of the Lights", duration: 5, album_id: a1.id)
Track.create(name: "Monster", duration: 7, album_id: a1.id)
Track.create(name: "So Appalled", duration: 7, album_id: a1.id)
Track.create(name: "Devil in a New Dress", duration: 6, album_id: a1.id)
Track.create(name: "Runaway", duration: 10, album_id: a1.id)
Track.create(name: "Hell of a Life", duration: 6, album_id: a1.id)
Track.create(name: "Blame Game", duration: 8, album_id: a1.id)
Track.create(name: "Lost in the World", duration: 5, album_id: a1.id)
Track.create(name: "Who will Survive in America", duration: 2, album_id: a1.id)

a2 = Album.create(cover: "http://s3.amazonaws.com/codecademy-content/projects/3/bass-music/beyonce.png", title: "Beyonce", artiste: "Beyonce")
Track.create(name: "Pretty Hurts", duration: 5, album_id: a2.id)
Track.create(name: "Haunted", duration: 7, album_id: a2.id)
Track.create(name: "Drunk in Love", duration: 6, album_id: a2.id)
Track.create(name: "Blow", duration: 6, album_id: a2.id)
Track.create(name: "No Angel", duration: 4, album_id: a2.id)
Track.create(name: "Partition", duration: 6, album_id: a2.id)
Track.create(name: "Jealous", duration: 4, album_id: a2.id)
Track.create(name: "Rocket", duration: 7, album_id: a2.id)
Track.create(name: "Mine", duration: 7, album_id: a2.id)
Track.create(name: "XO", duration: 4, album_id: a2.id)
Track.create(name: "Flawless", duration: 5, album_id: a2.id)
Track.create(name: "Superpower", duration: 5, album_id: a2.id)
Track.create(name: "Heaven", duration: 4, album_id: a2.id)
Track.create(name: "Blue", duration: 5, album_id: a2.id)

a3 = Album.create(cover: "http://s3.amazonaws.com/codecademy-content/projects/3/bass-music/21.png", title: "21", artiste: "Adele")
Track.create(name: "Rolling in the Deep", duration: 4, album_id: a3.id)
Track.create(name: "Rumour Has It", duration: 4, album_id: a3.id)
Track.create(name: "Turning Tables", duration: 5, album_id: a3.id)
Track.create(name: "Don't You Remember", duration: 5, album_id: a3.id)
Track.create(name: "Set Fire to the Rain", duration: 5, album_id: a3.id)
Track.create(name: "He Won't Go", duration: 5, album_id: a3.id)
Track.create(name: "Take it All", duration: 4, album_id: a3.id)
Track.create(name: "I'll be Waiting", duration: 5, album_id: a3.id)
Track.create(name: "One and Only", duration: 6, album_id: a3.id)
Track.create(name: "Lovesong", duration: 6, album_id: a3.id)

a4 = Album.create(cover: "http://s3.amazonaws.com/codecademy-content/projects/3/bass-music/channel-orange.jpg", title: "Channel Orange", artiste: "Frank Ocean")
Track.create(name: "Start", duration: 1, album_id: a4.id)
Track.create(name: "Thinkin Bout You", duration: 4, album_id: a4.id)
Track.create(name: "Fertilizer", duration: 1, album_id: a4.id)
Track.create(name: "Sierra Leone", duration: 3, album_id: a4.id)
Track.create(name: "Sweet Life", duration: 5, album_id: a4.id)
Track.create(name: "Not Just Money", duration: 1, album_id: a4.id)
Track.create(name: "Super Rich Kids", duration: 6, album_id: a4.id)
Track.create(name: "Pilot Jones", duration: 4, album_id: a4.id)
Track.create(name: "Crack Rock", duration: 4, album_id: a4.id)
Track.create(name: "Pyramids", duration: 10, album_id: a4.id)
Track.create(name: "Lost", duration: 4, album_id: a4.id)
Track.create(name: "White", duration: 2, album_id: a4.id)
Track.create(name: "Monks", duration: 4, album_id: a4.id)
Track.create(name: "Bad Religion", duration: 3, album_id: a4.id)
Track.create(name: "Pink Matter", duration: 5, album_id: a4.id)
Track.create(name: "Forrest Gump", duration: 4, album_id: a4.id)
Track.create(name: "End/Golden Girl", duration: 9, album_id: a4.id)

a5 = Album.create(cover: "http://s3.amazonaws.com/codecademy-content/projects/3/bass-music/good-kid-maad-city.jpg", title: "Good Kid, M.A.A.D City", artiste: "Kendrick Lamar")
Track.create(name: "Sherane a.k.a. Master Splinterâ€™s Daughter", duration: 5, album_id: a5.id)
Track.create(name: "Bitch, Don't Kill My Vibe", duration: 6, album_id: a5.id)
Track.create(name: "Backseat Freestyle", duration: 4, album_id: a5.id)
Track.create(name: "The Art of Peer Pressure", duration: 6, album_id: a5.id)
Track.create(name: "Money Trees", duration: 7, album_id: a5.id)
Track.create(name: "Poetic Justice", duration: 5, album_id: a5.id)
Track.create(name: "good kid", duration: 4, album_id: a5.id)
Track.create(name: "m.A.A.d city", duration: 6, album_id: a5.id)
Track.create(name: "Swimming Pools (Drank)", duration: 6, album_id: a5.id)
Track.create(name: "Sing About Me, Iâ€™m Dying of Thirst", duration: 13, album_id: a5.id)
Track.create(name: "Real", duration: 8, album_id: a5.id)
Track.create(name: "Compton", duration: 5, album_id: a5.id)

a6 = Album.create(cover: "http://s3.amazonaws.com/codecademy-content/projects/3/bass-music/ram.jpg", title: "Random Access Memories", artiste: "Daft Punk")
Track.create(name: "Give Life Back to Music", duration: 5, album_id: a6.id)
Track.create(name: "The Game of Love", duration: 6, album_id: a6.id)
Track.create(name: "Giorgio by Moroder", duration: 10, album_id: a6.id)
Track.create(name: "Within", duration: 4, album_id: a6.id)
Track.create(name: "Instant Crush", duration: 6, album_id: a6.id)
Track.create(name: "Lose Yourself to Dance", duration: 6, album_id: a6.id)
Track.create(name: "Touch", duration: 9, album_id: a6.id)
Track.create(name: "Get Lucky", duration: 7, album_id: a6.id)
Track.create(name: "Beyond", duration: 5, album_id: a6.id)
Track.create(name: "Motherboard", duration: 6, album_id: a6.id)
Track.create(name: "Fragments of Time", duration: 5, album_id: a6.id)
Track.create(name: "Doin' It Right", duration: 5, album_id: a6.id)
Track.create(name: "Contact", duration: 7, album_id: a6.id)

a7 = Album.create(cover: "http://s3.amazonaws.com/codecademy-content/projects/3/bass-music/the-2020-experience.png", title: "The 20/20 Experience", artiste: "Justin Timberlake")
Track.create(name: "Pusher Love Girl", duration: 9, album_id: a7.id)
Track.create(name: "Suit & Tie", duration: 6, album_id: a7.id)
Track.create(name: "Don't Hold the Wall", duration: 8, album_id: a7.id)
Track.create(name: "Strawberry Bubblegum", duration: 8, album_id: a7.id)
Track.create(name: "Tunnel Vision", duration: 7, album_id: a7.id)
Track.create(name: "Spaceship Coupe", duration: 8, album_id: a7.id)
Track.create(name: "That Girl", duration: 5, album_id: a7.id)
Track.create(name: "Let the Groove Get In", duration: 8, album_id: a7.id)
Track.create(name: "Mirrors", duration: 9, album_id: a7.id)
Track.create(name: "Blue Ocean Floor", duration: 8, album_id: a7.id)